

export const myProjectInfo = [
    {
        id:1,
        demoLink:"",
        gitLink:"",
        image:"",
        title:"Project-1"
    },
    {
        id:2,
        demoLink:"",
        gitLink:"",
        image:"",
        title:"Project-2"
    },
    {
        id:3,
        demoLink:"",
        gitLink:"",
        image:"",
        title:"Project-3"
    },
    {
        id:4,
        demoLink:"",
        gitLink:"",
        image:"",
        title:"Project-4"
    },
    {
        id:5,
        demoLink:"",
        gitLink:"",
        image:"",
        title:"Project-5"
    },
    {
        id:6,
        demoLink:"",
        gitLink:"",
        image:"",
        title:"Project-6"
    },
    {
        id:7,
        demoLink:"",
        gitLink:"",
        image:"",
        title:"Project-7"
    },
    {
        id:8,
        demoLink:"",
        gitLink:"",
        image:"",
        title:"Project-8"
    },
]